# General column names
PARAMS_COLUMN_NAME = 'params'
PARAMS_EMULATOR_COLUMN_NAME = 'params_emulator'

# Column names for a specific model_selection
RMSE_TRAIN_COLUMN_NAME = 'RMSE_train'
RMSE_VALIDATION_COLUMN_NAME = 'RMSE_validation'
COMPLEXITY_COLUMN_NAME = 'complexity'
EXPR_COLUMN_NAME = 'expr'
VARIABLE_NAMES_COLUMN_NAME = 'variable_names'

COLUMN_NAMES = [RMSE_TRAIN_COLUMN_NAME, RMSE_VALIDATION_COLUMN_NAME, COMPLEXITY_COLUMN_NAME, EXPR_COLUMN_NAME,
                VARIABLE_NAMES_COLUMN_NAME]







