from optimization.optimization_marginal.optimization_marginal import OptimizationMarginal
from optimization.optimization_random.optimimization_random_zoo import OptimizationRandom_500, OptimizationRandom_200_5
from optimization.optmization_pipeline.optimization_pipeline_factory import optimization_pipeline_factory

OptimizationPipelineRandom = OptimizationRandom_500
OptimizationPipelineMarginalRandom = optimization_pipeline_factory([OptimizationMarginal, OptimizationRandom_200_5])

optimization_types_500 = [OptimizationPipelineRandom, OptimizationPipelineMarginalRandom][1:]