from optimization.optimization_bayesian.opitmization_bayesian_factory import optimization_bayesian_factory


OptimizationBayesian_500 = optimization_bayesian_factory(500)
OptimizationBayesian_400 = optimization_bayesian_factory(400)
OptimizationBayesian_2 = optimization_bayesian_factory(2)
OptimizationBayesian_5 = optimization_bayesian_factory(5)
OptimizationBayesian_10 = optimization_bayesian_factory(10)
OptimizationBayesian_20 = optimization_bayesian_factory(20)
OptimizationBayesian_210_5 = optimization_bayesian_factory(210, 5)
OptimizationBayesian_200_5 = optimization_bayesian_factory(200, 5)
OptimizationBayesian_100_5 = optimization_bayesian_factory(100, 5)